name: 'Example summaries'
on:
  push:

jobs:
  with-variables:
    name: 'Template with dynamic data'
    runs-on: ubuntu-22.04
    steps:
      - name: 'Template without variables'
        uses: WcAServices/markdown-template-action@main
        with:
          # language="bashpro shell script"
          variables: >-
            GREETING="World"
            COMMIT_SHA="${{ github.sha }}"
            SHORT_SHA=${COMMIT_SHA:0:7}

          # language="markdown"
          template: |
            # Hello, $GREETING
            > ### You're on commit [`$SHORT_SHA`]($COMMIT_SHA)            
              
            ##### Standard GitHub variables should work too:
            ```yaml
            Github Ref: $GITHUB_REF
            Commit author: $GITHUB_ACTOR
            Job: $GITHUB_JOB
            ```
              
  without-variables:
    name: 'Static template'
    runs-on: ubuntu-22.04
    steps:
      - name: 'Template without variables'
        uses: WcAServices/markdown-template-action@main
        with:
          # language="markdown"
          template: |
            # Without variables
            > Just a standard Markdown template with nothing fancy going on.